name = "OMBackend"
uuid = "9400bd5f-7561-42f6-8760-03756753da50"
authors = ["John Tinnerholm <johti17@liu.se>", "Karim Abdelhak <karim.abdelhak@fh-bielefeld.de>", "AnHeuermann <andreas.heuermann@fh-bielefeld.de>"]
version = "0.4.3"

[deps]
Absyn = "ce2f92e2-a952-11e9-0543-8b443f216f1d"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DAE = "0174eeea-c361-11e9-3d0d-a9ca8048aff6"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DoubleEnded = "1bc4e7c2-c1e1-11e9-03fe-315bbef43fde"
ExportAll = "ad2082ca-a69e-11e9-38fa-e96309a31fe4"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ImmutableList = "4a558cac-c1ed-11e9-20da-3584bcd8709a"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
MetaModelica = "9d7f2a79-07b5-5542-8b19-c0100dda6b06"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OMFrontend = "b10394b5-f439-4073-a0c5-e09cb00cf46c"
OMParser = "11f87224-cae7-4e99-a924-e50d12f62c59"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
SCode = "350d45b0-c210-11e9-3b9e-fdad65bb3d46"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
ListUtil="b2a72b7e-c1ef-11e9-3a87-6ddc5900c366"

[compat]
julia = "1.7"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
